
name: TicTacToe

description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  
  circular_countdown_timer: ^0.2.0
  firebase_auth: ^3.3.7
  firebase_database: ^9.0.6
  firebase_storage: ^10.2.7
  google_sign_in: ^5.2.4
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+9

  audioplayers: ^0.20.1
  path_provider: ^2.0.9
  google_mobile_ads: ^2.0.0

  flutter_inapp_purchase: ^5.1.2
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.20
  in_app_review: ^2.0.4
  share_plus: ^4.0.5
  the_apple_sign_in: ^1.1.1
  unity_ads_plugin: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/music/
    - assets/images/
    - assets/language/

  

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: DISPLATTER
      fonts:
        - asset: assets/fonts/DISPLATTER.OTF

